// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Provii

/**
 * Result Screen
 *
 * Displays the verification result (success or failure).
 */

import React from 'react';
import {View, Text, StyleSheet, TouchableOpacity} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootStackParamList} from '../../App';

type Props = NativeStackScreenProps<RootStackParamList, 'Result'>;

export default function ResultScreen({navigation, route}: Props) {
  const {verified, minimumAge, error} = route.params;

  const handleStartOver = () => {
    navigation.popToTop();
  };

  if (verified) {
    return (
      <View style={styles.container}>
        <View style={styles.content}>
          <View style={styles.successIcon}>
            <Text style={styles.iconText}>✓</Text>
          </View>

          <Text style={styles.successTitle}>Age Verified!</Text>

          <Text style={styles.subtitle}>
            The user has successfully proven they are {minimumAge} years or
            older.
          </Text>

          <View style={styles.infoCard}>
            <Text style={styles.infoTitle}>What happened:</Text>
            <View style={styles.infoBullet}>
              <Text style={styles.bulletDot}>•</Text>
              <Text style={styles.bulletText}>
                A zero knowledge proof was generated by Provii Wallet
              </Text>
            </View>
            <View style={styles.infoBullet}>
              <Text style={styles.bulletDot}>•</Text>
              <Text style={styles.bulletText}>
                The proof was verified cryptographically by the verifier backend
              </Text>
            </View>
            <View style={styles.infoBullet}>
              <Text style={styles.bulletDot}>•</Text>
              <Text style={styles.bulletText}>
                The user's actual date of birth was never revealed
              </Text>
            </View>
            <View style={styles.infoBullet}>
              <Text style={styles.bulletDot}>•</Text>
              <Text style={styles.bulletText}>
                The session was redeemed and can no longer be replayed
              </Text>
            </View>
          </View>

          <View style={styles.grantedCard}>
            <Text style={styles.grantedIcon}>🔓</Text>
            <Text style={styles.grantedText}>
              Access to age-restricted content can now be granted.
            </Text>
          </View>
        </View>

        <View style={styles.footer}>
          <TouchableOpacity style={styles.primaryButton} onPress={handleStartOver}>
            <Text style={styles.primaryButtonText}>Start Over</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  // Failure case
  return (
    <View style={styles.container}>
      <View style={styles.content}>
        <View style={styles.failureIcon}>
          <Text style={styles.iconText}>✕</Text>
        </View>

        <Text style={styles.failureTitle}>Verification Failed</Text>

        <Text style={styles.subtitle}>
          {error || `Unable to verify the user is ${minimumAge} years or older.`}
        </Text>

        <View style={styles.infoCard}>
          <Text style={styles.infoTitle}>Possible reasons:</Text>
          <View style={styles.infoBullet}>
            <Text style={styles.bulletDot}>•</Text>
            <Text style={styles.bulletText}>
              The user cancelled the verification
            </Text>
          </View>
          <View style={styles.infoBullet}>
            <Text style={styles.bulletDot}>•</Text>
            <Text style={styles.bulletText}>
              The verification challenge expired
            </Text>
          </View>
          <View style={styles.infoBullet}>
            <Text style={styles.bulletDot}>•</Text>
            <Text style={styles.bulletText}>
              The user doesn't meet the age requirement
            </Text>
          </View>
          <View style={styles.infoBullet}>
            <Text style={styles.bulletDot}>•</Text>
            <Text style={styles.bulletText}>
              A network or technical error occurred
            </Text>
          </View>
        </View>

        <View style={styles.deniedCard}>
          <Text style={styles.deniedIcon}>🔒</Text>
          <Text style={styles.deniedText}>
            Access to age-restricted content should be denied.
          </Text>
        </View>
      </View>

      <View style={styles.footer}>
        <TouchableOpacity style={styles.primaryButton} onPress={handleStartOver}>
          <Text style={styles.primaryButtonText}>Try Again</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  content: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#4caf50',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    marginBottom: 24,
  },
  failureIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#c62828',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    marginBottom: 24,
  },
  iconText: {
    fontSize: 36,
    color: '#fff',
    fontWeight: 'bold',
  },
  successTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4caf50',
    marginBottom: 12,
  },
  failureTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#c62828',
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 24,
  },
  infoCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    width: '100%',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
  },
  infoBullet: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  bulletDot: {
    fontSize: 14,
    color: '#666',
    marginRight: 8,
  },
  bulletText: {
    flex: 1,
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  grantedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e8f5e9',
    borderRadius: 12,
    padding: 16,
    width: '100%',
  },
  grantedIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  grantedText: {
    flex: 1,
    fontSize: 14,
    color: '#2e7d32',
    lineHeight: 20,
  },
  deniedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffebee',
    borderRadius: 12,
    padding: 16,
    width: '100%',
  },
  deniedIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  deniedText: {
    flex: 1,
    fontSize: 14,
    color: '#c62828',
    lineHeight: 20,
  },
  footer: {
    padding: 20,
  },
  primaryButton: {
    backgroundColor: '#1a73e8',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
