// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Provii

import SwiftUI

/// Displays the verification result after the polling flow completes.
///
/// Adapts messaging based on whether the verification succeeded or failed,
/// and whether the mode was over-age or under-age.
struct ResultView: View {
    /// Whether the age verification succeeded.
    let verified: Bool

    /// The age threshold that was verified against.
    let ageThreshold: Int

    /// The verification mode (over-age or under-age).
    let mode: VerificationMode

    /// An optional error message to display on failure.
    let errorMessage: String?

    @Environment(\.dismiss) private var dismiss

    var body: some View {
        VStack(spacing: 24) {
            Spacer()

            // Result icon
            if verified {
                Image(systemName: "checkmark.circle.fill")
                    .font(.system(size: 80))
                    .foregroundColor(.green)
                    .accessibilityLabel(String(localized: "Verification succeeded"))
            } else {
                Image(systemName: "xmark.circle.fill")
                    .font(.system(size: 80))
                    .foregroundColor(.red)
                    .accessibilityLabel(String(localized: "Verification failed"))
            }

            Text(verified ? String(localized: "Age Verified!") : String(localized: "Verification Failed"))
                .font(.title)
                .fontWeight(.bold)
                .foregroundColor(verified ? .green : .red)
                .accessibilityAddTraits(.isHeader)

            Text(resultDescription)
                .font(.body)
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)

            // Info card
            VStack(alignment: .leading, spacing: 12) {
                Text(verified ? String(localized: "What happened:") : String(localized: "Possible reasons:"))
                    .font(.headline)

                if verified {
                    BulletPoint(text: String(localized: "A zero knowledge proof was generated by Provii Wallet"))
                    BulletPoint(text: String(localized: "The proof was verified cryptographically"))
                    BulletPoint(text: proofDirectionBullet)
                    BulletPoint(text: String(localized: "No personal information was shared with this app"))
                } else {
                    BulletPoint(text: String(localized: "The user cancelled the verification"))
                    BulletPoint(text: String(localized: "The verification challenge expired"))
                    BulletPoint(text: failureAgeBullet)
                    BulletPoint(text: String(localized: "A network or technical error occurred"))
                }
            }
            .padding()
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(Color(.systemGray6))
            .cornerRadius(12)

            // Access card
            HStack {
                Image(systemName: verified ? "lock.open.fill" : "lock.fill")
                    .font(.title2)
                    .accessibilityLabel(verified ? String(localized: "Unlocked") : String(localized: "Locked"))

                Text(accessCardText)
                    .font(.subheadline)
            }
            .padding()
            .frame(maxWidth: .infinity)
            .background(verified ? Color.green.opacity(0.1) : Color.red.opacity(0.1))
            .foregroundColor(verified ? .green : .red)
            .cornerRadius(12)

            Spacer()

            NavigationLink(destination: AgeThresholdView()) {
                Text(verified ? String(localized: "Start Over") : String(localized: "Try Again"))
                    .fontWeight(.semibold)
                    .frame(maxWidth: .infinity)
                    .padding()
                    .background(Color.blue)
                    .foregroundColor(.white)
                    .cornerRadius(12)
            }
        }
        .padding()
        .navigationTitle(String(localized: "Result"))
        .navigationBarBackButtonHidden(true)
    }

    private var resultDescription: String {
        if verified {
            switch mode {
            case .overAge:
                return String(localized: "The user has successfully proven they are \(ageThreshold) years or older.")
            case .underAge:
                return String(localized: "The user has successfully proven they are under \(ageThreshold) years old.")
            }
        } else {
            switch mode {
            case .overAge:
                return errorMessage ?? String(localized: "Unable to verify the user is \(ageThreshold) years or older.")
            case .underAge:
                return errorMessage ?? String(localized:
                    "Unable to verify the user is under \(ageThreshold) years old.")
            }
        }
    }

    private var proofDirectionBullet: String {
        switch mode {
        case .overAge:
            return String(localized: "The user's actual date of birth was never revealed")
        case .underAge:
            return String(localized: "The user's actual date of birth was never revealed")
        }
    }

    private var failureAgeBullet: String {
        switch mode {
        case .overAge:
            return String(localized: "The user doesn't meet the minimum age requirement")
        case .underAge:
            return String(localized: "The user doesn't meet the maximum age requirement")
        }
    }

    private var accessCardText: String {
        if verified {
            switch mode {
            case .overAge:
                return String(localized: "Access to age-restricted content can now be granted.")
            case .underAge:
                return String(localized: "User qualifies for age-appropriate content.")
            }
        } else {
            switch mode {
            case .overAge:
                return String(localized: "Access to age-restricted content should be denied.")
            case .underAge:
                return String(localized: "User does not qualify for age-appropriate content.")
            }
        }
    }
}

/// A bullet point row for use in info cards.
struct BulletPoint: View {
    /// The text to display next to the bullet.
    let text: String

    var body: some View {
        HStack(alignment: .top, spacing: 8) {
            Text("\u{2022}")
                .foregroundColor(.secondary)
            Text(text)
                .font(.subheadline)
                .foregroundColor(.secondary)
        }
    }
}

#Preview("Verified - Over Age") {
    NavigationStack {
        ResultView(verified: true, ageThreshold: 21, mode: .overAge, errorMessage: nil)
    }
}

#Preview("Failed - Over Age") {
    NavigationStack {
        ResultView(verified: false, ageThreshold: 21, mode: .overAge, errorMessage: "Verification timed out")
    }
}

#Preview("Verified - Under Age") {
    NavigationStack {
        ResultView(verified: true, ageThreshold: 18, mode: .underAge, errorMessage: nil)
    }
}

#Preview("Failed - Under Age") {
    NavigationStack {
        ResultView(verified: false, ageThreshold: 18, mode: .underAge, errorMessage: nil)
    }
}
